version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    command: /entrypoint.sh
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./app:/opt/app

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis

  esearch:
    container_name: esearch
    image: elasticsearch:${ES_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

